### ISSUE TITLE
error in ggsurvplot due to specific form of fit

### ISSUE THREAD

**Issue by MarcinKosinski** [kassambara/survminer#86]
Hi again!

I am using ggsurvplot in RTCGA package - survminer is really helpful. Today I have noticed that RTCGA broke http://bioconductor.org/checkResults/release/bioc-LATEST/RTCGA/ due to the ERROR in `kmTCGA` function which is the only function that uses `ggsurvplot`.

I have found that for my data in the `kmTCGA` example the fit is so specific that it does not have calculated median of survival times (probably due to the small size of one group). This example was working for RTCGA ver 1.2.0 -> the last example from this staticdoc http://rtcga.github.io/RTCGA/staticdocs/kmTCGA.html but now it brokes in the newest version of survminer (but this hasn't changed for 2 months on CRAN, sic!). I think this must be due to the newest release of survival https://cran.r-project.org/web/packages/survival/index.html 

Do you think you can workaround this in `survminer` or can your provide any solution for that? RTCGA doesn't work, survminer neither : /

``` r
library(RTCGA.clinical)
library(dplyr)
# first extract survival info, then munge data                  
survivalTCGA(BRCA.clinical, 
             extract.cols = c("patient.drugs.drug.therapy_types.therapy_type"))  %>%
filter(patient.drugs.drug.therapy_types.therapy_type %in%
           c("chemotherapy", "hormone therapy")) %>%
rename(therapy = patient.drugs.drug.therapy_types.therapy_type) -> BRCA.survInfo.chemo

head(BRCA.survInfo.chemo)
```

      times bcr_patient_barcode patient.vital_status         therapy
    1  3767        TCGA-3C-AAAU                    0    chemotherapy
    2  1217        TCGA-3C-AALK                    0    chemotherapy
    3   158        TCGA-4H-AAAK                    0    chemotherapy
    4  1477        TCGA-5L-AAT0                    0 hormone therapy
    5  1471        TCGA-5L-AAT1                    0 hormone therapy
    6  1463        TCGA-A1-A0SF                    0 hormone therapy

``` r
table(BRCA.survInfo.chemo[, c(3,4)])
```

                        therapy
    patient.vital_status chemotherapy hormone therapy
                       0          469             266
                       1           18               7

``` r
# fit survival model
library(survival)
formu <- survival::Surv(times, patient.vital_status) ~ therapy
fit <- do.call(survival::survfit, list(formula = formu, data = BRCA.survInfo.chemo))
```

``` r
# create survival plots with survminer
library(survminer)
ggsurvplot(fit)

Error in `[[<-.data.frame`(`*tmp*`, variable, value = c(1L, NA, 1L, NA,  : 
  replacement has 1264 rows, data has 632
```

maybe this is the reason of `NA`s in the median and confidence intervals in the last table of the print of the `fit` object?

``` r
fit
```

    Call: survfit(formula = survival::Surv(times, patient.vital_status) ~ 
        therapy, data = structure(list(times = c(3767, 1217, 158, 
    1477, 1471, 1463, 434, 1437, 1196, 852, 584, 554, 3153, 548, 
    2179, 2365, 1950, 671, 1920, 1918, 1349, 764, 3820, 1827, 754, 
    3409, 2495, 2393, 2955, 2298, 1918, 158, 1870, 1750, 1288, 1339, 
    643, 761, 736, 496, 2758, 4088, 2181, 3021, 1903, 1001, 807, 
    770, 550, 2619, 1352, 1365, 1288, 1154, 337, 255, 456, 395, 321, 
    344, 397, 644, 550, 253, 289, 404, 379, 358, 326, 334, 268, 723, 
......
    "chemotherapy", "chemotherapy", "chemotherapy", "chemotherapy", 
    "chemotherapy", "hormone therapy", "hormone therapy", "chemotherapy", 
    "chemotherapy", "hormone therapy", "chemotherapy", "hormone therapy", 
    "hormone therapy", "hormone therapy", "hormone therapy", "chemotherapy", 
    "chemotherapy")), class = "data.frame", row.names = c(NA, -760L
    ), .Names = c("times", "bcr_patient_barcode", "patient.vital_status", 
    "therapy")))

                              n events median 0.95LCL 0.95UCL
    therapy=chemotherapy    487     18     NA      NA      NA
    therapy=hormone therapy 273      7     NA      NA      NA

Session info
============

``` r
devtools::session_info()
```

     setting  value                       
     version  R version 3.3.1 (2016-06-21)
     system   x86_64, linux-gnu           
     ui       X11                         
     language English                     
     collate  pl_PL.UTF-8                 
     tz       <NA>                        
     date     2016-12-01                  

     package        * version      date       source                               
     assertthat       0.1          2013-12-06 CRAN (R 3.3.1)                       
     backports        1.0.4        2016-10-24 CRAN (R 3.3.1)                       
     colorspace       1.3-1        2016-11-18 CRAN (R 3.3.1)                       
     data.table       1.9.8        2016-11-25 CRAN (R 3.3.1)                       
     DBI              0.5-1        2016-09-10 CRAN (R 3.3.1)                       
     devtools         1.12.0       2016-06-24 CRAN (R 3.3.1)                       
     digest           0.6.10       2016-08-02 CRAN (R 3.3.1)                       
     dplyr          * 0.5.0        2016-06-24 CRAN (R 3.3.1)                       
     evaluate         0.10         2016-10-11 cran (@0.10)                         
     ggplot2          2.2.0        2016-11-11 CRAN (R 3.3.1)                       
     ggthemes         3.3.0        2016-11-24 CRAN (R 3.3.1)                       
     gridExtra        2.2.1        2016-02-29 CRAN (R 3.3.1)                       
     gtable           0.2.0        2016-02-26 CRAN (R 3.3.1)                       
     htmltools        0.3.5        2016-03-21 CRAN (R 3.3.1)                       
     httr             1.2.1        2016-07-03 CRAN (R 3.3.1)                       
     knitr          * 1.15.1       2016-11-22 CRAN (R 3.3.1)                       
     lattice          0.20-34      2016-09-06 CRAN (R 3.3.1)                       
     lazyeval         0.2.0        2016-06-12 CRAN (R 3.3.1)                       
     magrittr         1.5          2014-11-22 CRAN (R 3.3.1)                       
     Matrix           1.2-7.1      2016-09-01 CRAN (R 3.3.1)                       
     memoise          1.0.0        2016-01-29 CRAN (R 3.3.1)                       
     munsell          0.4.3        2016-02-13 CRAN (R 3.3.1)                       
     plyr             1.8.4        2016-06-08 CRAN (R 3.3.1)                       
     purrr            0.2.2        2016-06-18 CRAN (R 3.3.1)                       
     R6               2.2.0        2016-10-05 CRAN (R 3.3.1)                       
     Rcpp             0.12.8       2016-11-17 CRAN (R 3.3.1)                       
     rmarkdown        1.2          2016-11-21 CRAN (R 3.3.1)                       
     rprojroot        1.1          2016-10-29 CRAN (R 3.3.1)                       
     RTCGA          * 1.5.0        2016-12-01 Bioconductor (R 3.3.1)               
     RTCGA.clinical * 20151101.4.0 2016-11-30 Bioconductor (R 3.3.1)               
     rvest            0.3.2        2016-06-17 CRAN (R 3.3.1)                       
     scales           0.4.1        2016-11-09 CRAN (R 3.3.1)                       
     stringi          1.1.2        2016-10-01 CRAN (R 3.3.1)                       
     stringr          1.1.0        2016-08-19 CRAN (R 3.3.1)                       
     survival       * 2.40-1       2016-10-30 CRAN (R 3.3.1)                       
     survminer        0.2.2.999    2016-11-23 Github (kassambara/survminer@56614b2)
     tibble           1.2          2016-08-26 CRAN (R 3.3.1)                       
     viridis          0.3.4        2016-03-12 CRAN (R 3.3.1)                       
     withr            1.0.2        2016-06-20 CRAN (R 3.3.1)                       
     XML              3.98-1.5     2016-11-10 CRAN (R 3.3.1)                       
     xml2             1.0.0        2016-06-24 CRAN (R 3.3.1)                       
     yaml             2.1.14       2016-11-12 CRAN (R 3.3.1)

**Comment by kassambara** [comment]
`surv_summary()` (v0.2.3) generated an error when the name of the variable used in `survfit()` can be found multiple times in the levels of the same variable. For example, variable = therapy; levels(therapy) --> "therapy" and "hormone therapy" ([#86](https://github.com/kassambara/survminer/issues/86)). This has been now fixed.

**Comment by MarcinKosinski** [comment]
I am still having this problem, even with 0.2.3 version
Any ideas where we can fix?

```{r}
Restarting R session...

> library(RTCGA.clinical)
Loading required package: RTCGA
Welcome to the RTCGA (version: 1.5.1).
> library(dplyr)

Attaching package: ‘dplyr’

The following objects are masked from ‘package:stats’:

    filter, lag

The following objects are masked from ‘package:base’:

    intersect, setdiff, setequal, union

> # first extract survival info, then munge data                  
> survivalTCGA(BRCA.clinical, 
+              extract.cols = c("patient.drugs.drug.therapy_types.therapy_type"))  %>%
+ filter(patient.drugs.drug.therapy_types.therapy_type %in%
+            c("chemotherapy", "hormone therapy")) %>%
+ rename(therapy = patient.drugs.drug.therapy_types.therapy_type) -> BRCA.survInfo.chemo
> 
> head(BRCA.survInfo.chemo)
  times bcr_patient_barcode patient.vital_status         therapy
1  3767        TCGA-3C-AAAU                    0    chemotherapy
2  1217        TCGA-3C-AALK                    0    chemotherapy
3   158        TCGA-4H-AAAK                    0    chemotherapy
4  1477        TCGA-5L-AAT0                    0 hormone therapy
5  1471        TCGA-5L-AAT1                    0 hormone therapy
6  1463        TCGA-A1-A0SF                    0 hormone therapy
> # fit survival model
> library(survival)
> formu <- survival::Surv(times, patient.vital_status) ~ therapy
> fit <- do.call(survival::survfit, list(formula = formu, data = BRCA.survInfo.chemo))
> 
> library(survminer)
Loading required package: ggplot2
> ggsurvplot(fit)
Error in `[[<-.data.frame`(`*tmp*`, variable, value = c(1L, NA, 1L, NA,  : 
  replacement has 1264 rows, data has 632
````

**Comment by MarcinKosinski** [comment]
I can add this example as a test for the future development.

**Comment by kassambara** [comment]
This issue has been normally fixed after releasing v0.2.3.  Please, install v0.2.3.999 from Github and let me know if it works...

**Comment by MarcinKosinski** [comment]
Ok I understand now, it has been fixed `AFTER` 0.2.3 relased. So it will be fixed with `0.2.4` relase on CRAN. 
It is not happening with 0.2.3.999
